### ISSUE TITLE
[Request] Channel name to support environment variables

### ISSUE THREAD

**Issue by agalpin** [Vincit/gocd-slack-task#3]
Would you be able to make the channel name support environment variables?

**Comment by juhasipo** [comment]
Parameters are actually already supported in all text fields since that is GoCD's default behaviour. I should state this more clearly in the documentation.

The support for environment variables requires a little bit of work but I'll start working on it.

**Comment by agalpin** [comment]
@juhasipo thanks didn't realize that parameters would work, should be fine for my use for now, would be happy waiting for environment variables. will change the request to remove parameters.

**Comment by juhasipo** [comment]
This is now fixed in version 1.3 (https://github.com/Vincit/gocd-slack-task/releases/tag/v1.3). I ended up adding a new channel type `Text` so that is's possible to control the target channel/user using the environment variable.

In version 1.3 it's now possible to use environment variables on any text field.
