### ISSUE TITLE
Upgrading to go.cd version 17.1 appears to break this plugin.

### ISSUE THREAD

**Issue by agalpin** [Vincit/gocd-slack-task#6]
We were on an earlier version of go.cd (16.8) and have recently updated to 17.1 and this task is no longer able to send messages and just fails now, tried updating the plugin but this didn't help.

**Comment by juhasipo** [comment]
Does GoCD give you any error in the UI or in the GoCD server logs (`/var/logs/go-server/plugin-slack.task.log`)?

**Comment by agalpin** [comment]
I was not able to find the file in question, but the message i get in the job log is 23:54:06.401 Error: Interaction with plugin with id 'slack.task' implementing 'task' extension failed while requesting for 'execute'. Reason: [Could not send message to slack]

**Comment by juhasipo** [comment]
I wonder if the GoCD server log (`/var/logs/go-server/go-server.log`) has stored the full stacktrace. That error message doesn't really give enough information. The cause is probably in the library that is actually sending the message to the Slack REST API. Or there might be something wrong with the contents of the message.

In any case I released version 1.3.1 of the plugin which should show the original exception error message in GoCD UI. It might help finding the cause to this issue if you can't find the full stacktrace in the logs.

https://github.com/Vincit/gocd-slack-task/releases/tag/v1.3.1

**Comment by agalpin** [comment]
new output is as follows:
22:30:35.283 Error: Interaction with plugin with id 'slack.task' implementing 'task' extension failed while requesting for 'execute'. Reason: [Could not send message to slack: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty]

**Comment by juhasipo** [comment]
@agalpin Sorry it took so long to answer. 

That error sounds like there is something wrong with the certificates. The cause may be that the Java installation has some problems. At one point at least Ubuntu had some issues with Java certs (https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/983302).

This might be a similar case http://askubuntu.com/questions/627426/minecraft-with-openjdk-7-i-get-the-trustanchors-parameter-must-be-non-empty with a possible fix.

**Comment by agalpin** [comment]
Yep this fixed it once i ran the following on the build agents.

dpkg --purge --force-depends ca-certificates-java && \
apt-get -y install ca-certificates-java && \
update-ca-certificates -f && \
